
const mockData = [
    { 
        id: 1, 
        city: "London", 
        name: 'LondonProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 2, 
        city: "London", 
        name: 'LondonProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 3, 
        city: "London", 
        name: 'LondonProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 4, 
        city: "London", 
        name: 'LondonProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 5, 
        city: "London", 
        name: 'LondonProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 6, 
        city: "London", 
        name: 'LondonProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    },
    { 
        id: 7, 
        city: "Paris", 
        name: 'ParisProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 8, 
        city: "Paris", 
        name: 'ParisProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 9, 
        city: "Paris", 
        name: 'ParisProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 10, 
        city: "Paris", 
        name: 'ParisProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 11, 
        city: "Paris", 
        name: 'ParisProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 12, 
        city: "Paris", 
        name: 'ParisProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    },
    { 
        id: 13, 
        city: "Mumbai", 
        name: 'MumbaiProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 14, 
        city: "Mumbai", 
        name: 'MumbaiProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 15, 
        city: "Mumbai", 
        name: 'MumbaiProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 16, 
        city: "Mumbai", 
        name: 'MumbaiProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 17, 
        city: "Mumbai", 
        name: 'MumbaiProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 18, 
        city: "Mumbai", 
        name: 'MumbaiProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    },
    { 
        id: 19, 
        city: "New York", 
        name: 'NewYorkProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 20, 
        city: "New York", 
        name: 'NewYorkProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 21, 
        city: "New York", 
        name: 'NewYorkProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 22, 
        city: "New York", 
        name: 'NewYorkProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 23, 
        city: "New York", 
        name: 'NewYorkProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 24, 
        city: "New York", 
        name: 'NewYorkProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    },
    { 
        id: 25, 
        city: "London", 
        name: 'LondonProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 26, 
        city: "London", 
        name: 'LondonProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 27, 
        city: "London", 
        name: 'LondonProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 28, 
        city: "London", 
        name: 'LondonProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 29, 
        city: "London", 
        name: 'LondonProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 30, 
        city: "London", 
        name: 'LondonProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    },
    { 
        id: 31, 
        city: "Paris", 
        name: 'ParisProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 32, 
        city: "Paris", 
        name: 'ParisProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 33, 
        city: "Paris", 
        name: 'ParisProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 34, 
        city: "Paris", 
        name: 'ParisProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 35, 
        city:"Paris", 
        name: 'ParisProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 36, 
        city: "Paris", 
        name: 'ParisProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    },
    { 
        id: 37, 
        city: "Mumbai", 
        name: 'MumbaiProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 38, 
        city: "Mumbai", 
        name: 'MumbaiProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 39, 
        city: "Mumbai", 
        name: 'MumbaiProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 40, 
        city: "Mumbai", 
        name: 'MumbaiProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 41, 
        city: "Mumbai", 
        name: 'MumbaiProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 42, 
        city: "Mumbai", 
        name: 'MumbaiProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    },
    { 
        id: 43, 
        city: "New York", 
        name: 'NewYorkProperty1', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '732 sqft', 
        price: '2500', 
        type: 'House', 
        imageUrl: 'images/property1.jpg' 
    },
    { 
        id: 44, 
        city: "New York", 
        name: 'NewYorkProperty2', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '624 sqft', 
        price: '2200', 
        type: 'Apartment', 
        imageUrl: 'images/property2.jpg' 
    },
    { 
        id: 45, 
        city: "New York", 
        name: 'NewYorkProperty3', 
        rooms: '5', 
        beds: '4', 
        baths: '2', 
        area: '890 sqft', 
        price: '2700', 
        type: 'House', 
        imageUrl: 'images/property3.jpg' 
    },
    { 
        id: 46, 
        city: "New York", 
        name: 'NewYorkProperty4', 
        rooms: '2', 
        beds: '1', 
        baths: '1', 
        area: '510 sqft', 
        price: '1800', 
        type: 'Apartment', 
        imageUrl: 'images/property4.jpg' 
    },
    { 
        id: 47, 
        city: "New York", 
        name: 'NewYorkProperty5', 
        rooms: '3', 
        beds: '2', 
        baths: '1', 
        area: '672 sqft', 
        price: '2100', 
        type: 'Apartment', 
        imageUrl: 'images/property5.jpg' 
    },
    { 
        id: 48, 
        city: "New York", 
        name: 'NewYorkProperty6', 
        rooms: '4', 
        beds: '3', 
        baths: '2', 
        area: '768 sqft', 
        price: '2400', 
        type: 'House', 
        imageUrl: 'images/property6.jpg' 
    }

];

export default mockData;